### ISSUE TITLE
How do i add torrent trackers in colab?

### ISSUE THREAD

**Issue by Psp29onetwo** [r12habh/Torrent-To-Google-Drive-Downloader#13]
I want to add torrent trackers in colab because my downloading speed in colab is 0.00kbps and when i add trackers in uTorrent for the same torrent speed increased but how can i add those trackers in colab as well so that my download catch some speed.

**Comment by r12habh** [comment]
@Psp29onetwo Try this https://stackoverflow.com/questions/51137770/libtorrent-add-multiple-tracker-in-magnet-link-uri
And let me know if it worked.
