### ISSUE TITLE
UI for this app

### ISSUE THREAD

**Issue by r12habh** [r12habh/Torrent-To-Google-Drive-Downloader#31]
https://anvil.works/learn/tutorials/google-colab-to-web-app

@ethanaobrien
Can you look if it is possible to create a UI for this app?

And I have created v4.1 by removing duplicate code.

**Comment by ethanaobrien** [comment]
@r12habh Thanks, Thats the one part I couldnt figure out how to do. Yes, a UI would be really cool for this app. I'll look into it when I get a chance

**Comment by ethanaobrien** [comment]
@r12habh I took a look at it and it looks like the way anvil works, we would need to manually go in and start the google colab notebook every time. Also, I couldnt find a way to output the text from the linking google drive - Especially since this part requires input.

**Comment by r12habh** [comment]
@ethanaobrien  I explored some other options too, I don't think it's possible to create the kind of UI we want on Google Colab.

**Comment by ethanaobrien** [comment]
@r12habh Yeah, It would be really cool (Like REALLY cool) but I am not sure that it is possible.

**Comment by r12habh** [comment]
@ethanaobrien There is a lot of material regarding this on StackOverflow and the end answer is the same, i.e., not possible.
And one another option is: https://www.youtube.com/watch?v=oIVmV41uyK8

**Comment by r12habh** [comment]
@ethanaobrien 
should I close this? or have you found something

**Comment by ethanaobrien** [comment]
@r12habh No, I havent found anything. I do think it is somehow possible but it would most likely be easier to keep it the way it is.
